name: Update App

on:
  schedule:
    # Runs every 4 hours (At minute 0 past every 4th hour)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Allows you to trigger the action manually from GitHub

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request to Streamlit App
        run: |
          curl -sL -b "" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -o /dev/null https://biopredict.streamlit.app/